---
allowed_addresses:
  - "192.168.0.0/24"
  - "192.168.2.0/24"
  - "tty"
allowed_users:
  - "john"
  - "doe"
recheck_time: 30
grace_time: 1800

mail:
  from: "loginwatch@example.org"
  from_name: "Login Alert"
  subject: "Not allowed login detected"
  recipients:
    - "alert@example.org"
    - "sms@example.org"

slack:
  webhook_url: "https://hooks.slack.com/services/foo/bar/baz"
  channel: "#alerts"
  author: "Login Watcher"
  message: "Not allowed login detected"
  username: "abot"
  icon_emoji: ":alien:"