---
mail_from: "loginwatch@example.org"
mail_from_name: "Login Alert"
mail_subject: "Not allowed login detected"
mail_to:
  - "alert@example.org"
  - "sms@example.org"
allowed_addresses:
  - "192.168.0.0/24"
  - "192.168.2.0/24"
  - "tty"
recheck_time: 30
grace_time: 1800
